name: Update iCal feed

on:
  workflow_dispatch:
  schedule:
    - cron: "17 * * * *"  # hourly (UTC)

permissions:
  contents: write

concurrency:
  group: "ical-update"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate feed
        run: |
          python -m lolesports_ical --out docs/feed.ics --tz Europe/Berlin --days 30

      - name: Commit if changed
        run: |
          if git diff --quiet; then
            echo "No changes."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/feed.ics
          git commit -m "Update feed.ics"
          git push